### ISSUE TITLE
unknown command

### ISSUE THREAD

**Issue by 2020-maker** [p2sr/srconfigs#37]
when i do anything unusual fullbright etc, it says unknown commad: the bind ex: fullbright

**Comment by JaioCG** [comment]
Not quite sure what this means, but I'm gonna assume you're seeing a ton of "unknown command"s in console because you don't have SAR installed. Follow this video guide to get srconfigs properly set up. https://www.youtube.com/watch?v=fnFenfXjrtg

**Comment by 2020-maker** [comment]
The issue was that i didn't extract the files of srconfig

**Comment by ThisAMJ** [comment]
Vote to close as resolved
