### ISSUE TITLE
toasts broken

### ISSUE THREAD

**Issue by JaydenDev** [p2sr/srconfigs#44]
Basically, the dialog toasts are stuck on one small bit of dialog. And the part that shows the map, shows the previous map.

**Comment by ThisAMJ** [comment]
- Which small bit of dialogue? If it is `[no fade]`, that just means there isn't any dialogue for that map.
- You're in coop? Blue or Orange?
- Which map are you on? Does it only happen on this map?
- Have you modified the configs at all? If so, what have you changed?
- Do you have a specific set of steps to reproduce this behavior?

**Comment by JaydenDev** [comment]
I'm using those versions of srconfigs and sar
Most of the time the ending of the dialog
coop and sp, red and orange
all maps
ive only changed the UI text size, but the issue was there before

steps
1. install srconfigs
2. load up any map with dialogue
3. see a small portion of the dialogue in the second to last black box. it wont change, its just stuck

**Comment by JaydenDev** [comment]
It randomely fixed itself...? Im yet to test coop again tho

**Comment by JaydenDev** [comment]
tested on coop, fixed

**Comment by JaydenDev** [comment]
update: it being 'fixed' was just toasts not working.

**Comment by mlugg** [comment]
can you send a screenshot or something to demonstrate what you actually mean

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/179124151-9c0a4a3c-94d0-4e06-8110-335a25575fba.png)

**Comment by JaydenDev** [comment]
doesn't scroll through, just one part

**Comment by mlugg** [comment]
I think you've misunderstood what this feature is. It's not subtitles or anything like that; it shows you the dialogue fades for optimal timesave.

**Comment by JaydenDev** [comment]
well, good to know..
