### ISSUE TITLE
[feat] solocoop categories

### ISSUE THREAD

**Issue by ThatFridgeFella** [p2sr/srconfigs#46]
AMJ told me to make an issue for suggestions:

Solocoop Practice Category (Blue or orange as the fullscreen view)
Solocoop Running Category (Blue and orange splitscreen)

**Comment by ThisAMJ** [comment]
It'd be more convenient to have just one category, would you agree to an svar along the lines of `solocoop_fullscreen`?

**Comment by ThisAMJ** [comment]
Resolved by c6137bd
