### ISSUE TITLE
Support both Reloaded versions

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/srconfigs#53]
Going back to 1.0.0 from latest means binds for att1 and att2 will persist. Best fix is to use `key_findbinding` (yay!) and bind att1 back to +attack etc.

The annoying part is that the reverse is true for going forward to latest, since orange's right click to close time portal doesnt work on +attack2.

**Comment by mlugg** [comment]
I've not kept up with how this works at all, but: is there any reason we can't just have an alias which is remapped based on the version?

(Also, how do we detect the version? If it's not already a thing, I'd be fine to consider them separate games in SAR for `cond`.)

**Comment by ThisAMJ** [comment]
> just have an alias which is remapped based on the version

Yeah, but the problem is that `att1`-3 are not + binds, meaning if we just alias them to `+attack` it'll be held down, and `att1`gang is hard-coded to be bound by the maps. The solution is the combination of the SAR branch that blocks the maps from doing this rebinding, and binding it instead to, I suppose, `+att1` which would be `conds coop "etc" "+attack $1"` etc

The binding would be checking the bind for mouse1, if it's exactly `att1` rebind it to `+att1`. Very doable, and the same could be done for `+attack3` (currently we have users bind it manually), and maybe even mwheelup/down if they're at the default.
